### PR TITLE
personal data-reserve to prevent loss RFC

### PR DESCRIPTION
**Pull request by gitaaron**
Nothing to see here yet - just a template to add PR # to doc

### CODE REVIEW

**Review by farhoud — COMMENTED** [review]
I think we can leave local pool out of this

**Comment by gitaaron** [comment]
> I think we can leave local pool out of this

Can you clarify what you  mean  by  'local pool'?

**Comment by gitaaron** [comment]
Here are a few thoughts on reducing scope -

1.  Include 'free from conflicts due to real-time user updates' as a pre-condition.  Create a separate design doc for 'data sharing' that covers the following story -
"I want to share my data set with another device so that they both can read/update them in real-time."

2.  Create a separate design doc for local data backups.

3.  Link to https://github.com/functionland/docs/blob/main/docs/RFCs/pnet.md

**Comment by ehsan6sha** [comment]
@gitaaron for number 4: it adds another layer of potential failure to the system, and since Libp2p provides some features that we probably can come out good without VPN, I don't think we should add this complication.

**Pull request closed without merging**
